/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebank;

import java.awt.Frame;
import javax.swing.JFrame;

/**
 *
 * @author Alex'sCucumbah
 */
public class CajeroJDialog extends javax.swing.JDialog {
    
    int posTar;
    Banco eBanco;
    
    
    public CajeroJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CajeroJDialog(java.awt.Frame parent, String title, boolean modal, Banco eBanco, int posTar) {
        super(parent, title, modal);       
        this.eBanco = eBanco;        
        this.posTar = posTar;        
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTerTJT = new javax.swing.JLabel();
        jButtonConsultarSaldo = new javax.swing.JButton();
        jButtonReintegro = new javax.swing.JButton();
        jButtonIngreso = new javax.swing.JButton();
        jButtonCambioPin = new javax.swing.JButton();
        jButtonTransferencia = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Operaciones con tarjeta acabada en: ");

        jLabelTerTJT.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelTerTJT.setText('*' + eBanco.gettTarjetas()[posTar].getNumTarjeta().substring(12));

        jButtonConsultarSaldo.setText("Consultar Saldo");
        jButtonConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarSaldoActionPerformed(evt);
            }
        });

        jButtonReintegro.setText("Retirar dinero");
        jButtonReintegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReintegroActionPerformed(evt);
            }
        });

        jButtonIngreso.setText("Ingresar dinero");
        jButtonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresoActionPerformed(evt);
            }
        });

        jButtonCambioPin.setText("Cambiar PIN");
        jButtonCambioPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambioPinActionPerformed(evt);
            }
        });

        jButtonTransferencia.setText("Transferencia a otra cuenta");
        jButtonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferenciaActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonIngreso)
                            .addComponent(jButtonReintegro)
                            .addComponent(jButtonConsultarSaldo))
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonTransferencia)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCambioPin, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTerTJT, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTerTJT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarSaldo)
                    .addComponent(jButtonTransferencia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReintegro)
                    .addComponent(jButtonCambioPin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIngreso)
                    .addComponent(jButtonSalir))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarSaldoActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "El saldo actual de su tarjeta es de: " + eBanco.gettTarjetas()[posTar].getSaldo()+"€");
    }//GEN-LAST:event_jButtonConsultarSaldoActionPerformed

    private void jButtonCambioPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambioPinActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        NuevoPINJDialog ressetpin = new NuevoPINJDialog(frame, "Cambio de PIN" ,eBanco, posTar);
        ressetpin.setVisible(true);
    }//GEN-LAST:event_jButtonCambioPinActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonReintegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReintegroActionPerformed
        // TODO add your handling code here:
        int error=0;
        double cantidad = 0.0;
        
        try{
           cantidad = Double.parseDouble(javax.swing.JOptionPane.showInputDialog("Introduzca la cantidad de dinero a retirar")); 
           error = eBanco.gettTarjetas()[posTar].reintegro(cantidad);
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,"Error, la cantidad a retirar ha de ser un número decimal, separado por un punto (.)");             
        }
        
        
        switch (error){
            case 0: 
                break;
            case 1:
                javax.swing.JOptionPane.showMessageDialog(this, "Error, la cantidad introducida ha de ser positiva");
                break;
            case 2:
                javax.swing.JOptionPane.showMessageDialog(this, "Error, la cantidad introducida no puede exceder el saldo de la Tarjeta: " + eBanco.gettTarjetas()[posTar].getSaldo() + "€");
                break;
            case 3:
                javax.swing.JOptionPane.showMessageDialog(this, "Error, la cantidad introducida no puede exceder los " + Banco.LIMITE_REINTEGRO + " €.");
                break;
            case 4:
                javax.swing.JOptionPane.showMessageDialog(this, "Se han retirado "+ cantidad +"€ satisfactoriamente");
                eBanco.guardar(BancoConIgSerializado.NOMBREFICHERO);
                break;
        }
        
    }//GEN-LAST:event_jButtonReintegroActionPerformed

    private void jButtonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresoActionPerformed
        // TODO add your handling code here:
        int error=0;
        double cantidad = 0.0;
        
        try{
           cantidad = Double.parseDouble(javax.swing.JOptionPane.showInputDialog("Introduzca la cantidad de dinero a ingresar")); 
           error = eBanco.gettTarjetas()[posTar].ingreso(cantidad);
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,"Error, la cantidad a ingresar ha de ser un número decimal, separado por un punto (.)");             
        }
        
        switch (error){
            case 0: 
                break;
            case 1:
                javax.swing.JOptionPane.showMessageDialog(this, "Error, la cantidad introducida ha de ser positiva");
                break;
            case 2:
                javax.swing.JOptionPane.showMessageDialog(this, "Error, la cantidad introducida no puede exceder los " + Banco.LIMITE_INGRESO + " €.");
                break;
            case 3:
                javax.swing.JOptionPane.showMessageDialog(this, "Se han ingresado "+ cantidad +"€ satisfactoriamente. Su nuevo saldo es " + eBanco.gettTarjetas()[posTar].getSaldo()+ "€");
                eBanco.guardar(BancoConIgSerializado.NOMBREFICHERO);
                break;
        }
    }//GEN-LAST:event_jButtonIngresoActionPerformed

    private void jButtonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferenciaActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        CajeroLogInJDialog login = new CajeroLogInJDialog(frame, "Cuenta remitente de transferencia", eBanco, posTar);
        login.setVisible(true);
        
    }//GEN-LAST:event_jButtonTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajeroJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajeroJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajeroJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajeroJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CajeroJDialog dialog = new CajeroJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambioPin;
    private javax.swing.JButton jButtonConsultarSaldo;
    private javax.swing.JButton jButtonIngreso;
    private javax.swing.JButton jButtonReintegro;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTerTJT;
    // End of variables declaration//GEN-END:variables
}
