/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebank;


import javax.swing.JFrame;

/**
 *
 * @author Alex'sCucumbah
 */
public class ContadorPINJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewContadorPINJDialog
     */
    
    int posTar;
    int contIntentos = 0;
    Banco eBanco;
    
    public ContadorPINJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
              
    }
    
    public ContadorPINJDialog(java.awt.Frame parent, boolean modal, Banco eb, int pT) {
        super(parent, modal);        
        eBanco = eb;        
        posTar = pT;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldPIN = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabelContador = new javax.swing.JLabel();
        jLabelTerTJT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PIN");

        jPasswordFieldPIN.setText("Introduzca aquí su PIN");
        jPasswordFieldPIN.setToolTipText("Introduzca aquí su PIN");
        jPasswordFieldPIN.setEchoChar((char)0);
        jPasswordFieldPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPINActionPerformed(evt);
            }
        });
        jPasswordFieldPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPINKeyPressed(evt);
            }
        });

        jLabel2.setText("Intentos Restantes");

        jLabelContador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelContador.setText("3");

        jLabelTerTJT.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelTerTJT.setText('*' + eBanco.gettTarjetas()[posTar].getNumTarjeta().substring(12));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Introduzca el pin de la tarjeta acabada en: ");

        jButton1.setText("Acteptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordFieldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTerTJT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelContador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTerTJT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelContador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPINActionPerformed
        //TODO add your handling code here
        if (eBanco.gettTarjetas()[posTar].getPin().compareTo(String.valueOf(jPasswordFieldPIN.getPassword())) != 0){
        contIntentos++;
            if (contIntentos != 3) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Pin erroneo, le quedan " + (3 - contIntentos) + " intentos");
                    jLabelContador.setText(String.valueOf(3 - contIntentos));                    
                    jPasswordFieldPIN.setColumns(4);
                    jPasswordFieldPIN.setText("");
               }else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Pin erroneo, no le quedan más intentos, su tarjeta ha sido bloqueada");
                    jLabelContador.setText(String.valueOf(3 - contIntentos));
                    eBanco.gettTarjetas()[posTar].setBloqueada(true);
                    eBanco.guardar(BancoConIgSerializado.NOMBREFICHERO);
                    super.dispose();
                }
                
        }else{
            dispose();
            //quiero llamar al padre para cerrarlo cuando el pin sea correcto 
            JFrame frame = new JFrame();
            CajeroJDialog cajero = new CajeroJDialog(frame,"Operaciones con Tarjeta", false, eBanco, posTar);
            cajero.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jPasswordFieldPINActionPerformed

    private void jPasswordFieldPINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPINKeyPressed
        // TODO add your handling code here: \u25cf
        
        if (String.valueOf(jPasswordFieldPIN.getPassword()).compareTo("Introduzca aquí su PIN") == 0) {
            jPasswordFieldPIN.setText("");
            jPasswordFieldPIN.setEchoChar('\u25cf');
        }
        
    }//GEN-LAST:event_jPasswordFieldPINKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPasswordFieldPINActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorPINJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorPINJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorPINJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorPINJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContadorPINJDialog dialog = new ContadorPINJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelContador;
    private javax.swing.JLabel jLabelTerTJT;
    private javax.swing.JPasswordField jPasswordFieldPIN;
    // End of variables declaration//GEN-END:variables
}
