/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebank;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex'sCucumbah
 */
public class LogInNumTarjetaJDialog extends javax.swing.JDialog {

    /**
     * Creates new form logInNumTarjetaJDialog
     */
    private Banco eBanco;
    private int posTar;
    private boolean tipo; //Si es tipo baja, true. Si es tipo modificacion, false
    public LogInNumTarjetaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public LogInNumTarjetaJDialog(java.awt.Frame parent, String title, Banco banco) {
        super(parent, title);
        eBanco = banco;
        initComponents();
        
        jButtonAceptarBaja.setVisible(false);
        jButtonAceptarModificacion.setVisible(false);
        
        if (title.compareTo("Dar de Baja") == 0) {
            tipo=true;
        }else{
            tipo=false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxBloqueada = new javax.swing.JCheckBox();
        jButtonAceptarBaja = new javax.swing.JButton();
        jButtonAceptarModificacion = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldSaldo = new javax.swing.JTextField();
        jTextFieldPIN = new javax.swing.JTextField();
        jLabelVerificacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Numero Tarjeta");

        jTextFieldNumTarjeta.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jTextFieldNumTarjeta.setText("Número de Tarjeta(16 Dígitos)");
        jTextFieldNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumTarjetaActionPerformed(evt);
            }
        });
        jTextFieldNumTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumTarjetaKeyPressed(evt);
            }
        });

        jLabel2.setText("Saldo");

        jLabel3.setText("PIN");

        jCheckBoxBloqueada.setText("Bloqueada");
        jCheckBoxBloqueada.setEnabled(false);
        jCheckBoxBloqueada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBloqueadaActionPerformed(evt);
            }
        });

        jButtonAceptarBaja.setText("Dar de Baja");
        jButtonAceptarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarBajaActionPerformed(evt);
            }
        });

        jButtonAceptarModificacion.setText("Aplicar Cambios");
        jButtonAceptarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarModificacionActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldSaldo.setEditable(false);
        jTextFieldSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoActionPerformed(evt);
            }
        });
        jTextFieldSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSaldoKeyPressed(evt);
            }
        });

        jTextFieldPIN.setEditable(false);
        jTextFieldPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPINActionPerformed(evt);
            }
        });
        jTextFieldPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPINKeyPressed(evt);
            }
        });

        jLabelVerificacion.setText("Verifique los campos pulsando Enter antes de aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVerificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBoxBloqueada))
                                    .addComponent(jTextFieldNumTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAceptarBaja)
                                    .addComponent(jButtonAceptarModificacion)
                                    .addComponent(jButtonCancelar))
                                .addGap(124, 124, 124)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelVerificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBoxBloqueada)
                    .addComponent(jTextFieldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jButtonAceptarModificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAceptarBaja)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumTarjetaActionPerformed
        // TODO add your handling code here:
        if(!TarjetaCredito.esNumTarjetaValido(jTextFieldNumTarjeta.getText())){
           javax.swing.JOptionPane.showMessageDialog(this,"Error el Número de la tarjeta esta compuesto unicamente por 16 dígitos numéricos");
        }else 
            if(eBanco.buscaPosicion(jTextFieldNumTarjeta.getText())==-1){
                javax.swing.JOptionPane.showMessageDialog(this,"Error este número de tarjeta no existe");
            }else{
                    jTextFieldNumTarjeta.setBackground(Color.green);
                    jTextFieldNumTarjeta.setEditable(false);
                    posTar = eBanco.buscaPosicion(jTextFieldNumTarjeta.getText());
                    
                    jTextFieldPIN.setText(eBanco.gettTarjetas()[posTar].getPin());
                    jTextFieldSaldo.setText(String.valueOf(eBanco.gettTarjetas()[posTar].getSaldo()));
                    jCheckBoxBloqueada.setSelected(eBanco.gettTarjetas()[posTar].isBloqueada());
                    
                    if (tipo) {
                        jButtonAceptarBaja.setVisible(true);
                    }else{
                        jButtonAceptarModificacion.setVisible(true);
                        jTextFieldPIN.setEditable(true);
                        jTextFieldSaldo.setEditable(true);
                        jCheckBoxBloqueada.setEnabled(true);
                        jLabelVerificacion.setVisible(true);
                    }
            }     
        
        
    }//GEN-LAST:event_jTextFieldNumTarjetaActionPerformed

    private void jTextFieldNumTarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumTarjetaKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldNumTarjeta.getText().compareTo("Número de Tarjeta(16 Dígitos)") == 0){
            this.jTextFieldNumTarjeta.setText("");
            jTextFieldNumTarjeta.setBackground(Color.red);
            jTextFieldNumTarjeta.setFont(new java.awt.Font("Tahoma", 0, 12));
        }
    }//GEN-LAST:event_jTextFieldNumTarjetaKeyPressed

    private void jCheckBoxBloqueadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBloqueadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxBloqueadaActionPerformed

    private void jButtonAceptarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarBajaActionPerformed
        // TODO add your handling code here:
        int res;
        
        res = javax.swing.JOptionPane.showConfirmDialog(this,"¿Estás seguro de borrar la cuenta asociada a esta tarjeta?" , "Dar de baja", JOptionPane.OK_CANCEL_OPTION); 
        if (res == javax.swing.JOptionPane.OK_OPTION) {
            eBanco.baja(posTar);
            eBanco.guardar(BancoConIgSerializado.NOMBREFICHERO);
            
            
            super.dispose();
        }else{
            
            super.dispose();            
        }
        
        
    }//GEN-LAST:event_jButtonAceptarBajaActionPerformed

    private void jButtonAceptarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarModificacionActionPerformed
        // TODO add your handling code here:
        if (jTextFieldPIN.getBackground() != Color.green || jTextFieldSaldo.getBackground() != Color.green){        
            javax.swing.JOptionPane.showMessageDialog(this, "Error alguno de los campos a modificar no es correcto, o aún no ha sido modificado");
        }else{
            eBanco.modificacion(posTar, 
                                Double.parseDouble(jTextFieldSaldo.getText()),
                                jTextFieldPIN.getText(),
                                jCheckBoxBloqueada.isSelected());
            eBanco.guardar(BancoConIgSerializado.NOMBREFICHERO);
            dispose();            
        }
    }//GEN-LAST:event_jButtonAceptarModificacionActionPerformed

    private void jTextFieldPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPINActionPerformed
        // TODO add your handling code here:
        if(!TarjetaCredito.esPinValido(jTextFieldPIN.getText())){
           javax.swing.JOptionPane.showMessageDialog(this,"Error el PIN ha de estar compuesto por 4 dígitos numéricos");
        }else{
            jTextFieldPIN.setBackground(Color.green);
            jTextFieldPIN.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldPINActionPerformed

    private void jTextFieldSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoActionPerformed
        // TODO add your handling code here:
        double saldo =0.0;
        boolean error = false;
        try{
           saldo = Double.parseDouble(jTextFieldSaldo.getText());          
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,"Error el valor introducido no es del formato esperado ej:123.12");
            error = true; 
        }
        if (saldo < 0 && !error) {
            javax.swing.JOptionPane.showMessageDialog(this,"Error el valor del saldo ha de ser 0 mayor que 0 y, en caso de ser decimal, ha de separarse mediante un punto(.)");
        }else if(!error){
            jTextFieldSaldo.setBackground(Color.green);
            jTextFieldSaldo.setEditable(false);
        }
        
    }//GEN-LAST:event_jTextFieldSaldoActionPerformed

    private void jTextFieldSaldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSaldoKeyPressed
        // TODO add your handling code here:
        if (jTextFieldSaldo.getText().compareTo(String.valueOf(eBanco.gettTarjetas()[posTar].getSaldo()))==0 &&  evt.getKeyCode()!= KeyEvent.VK_ENTER && !tipo) {
            jTextFieldSaldo.setText("");
        }
    }//GEN-LAST:event_jTextFieldSaldoKeyPressed

    private void jTextFieldPINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPINKeyPressed
        // TODO add your handling code here:
        if (jTextFieldPIN.getText().compareTo(eBanco.gettTarjetas()[posTar].getPin())==0 &&  evt.getKeyCode()!= KeyEvent.VK_ENTER && !tipo){
            jTextFieldPIN.setText("");
        }
    }//GEN-LAST:event_jTextFieldPINKeyPressed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
        super.dispose(); 
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInNumTarjetaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInNumTarjetaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInNumTarjetaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInNumTarjetaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogInNumTarjetaJDialog dialog = new LogInNumTarjetaJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarBaja;
    private javax.swing.JButton jButtonAceptarModificacion;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBoxBloqueada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelVerificacion;
    private javax.swing.JTextField jTextFieldNumTarjeta;
    private javax.swing.JTextField jTextFieldPIN;
    private javax.swing.JTextField jTextFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
